eureka.client.enabled=false
spring.cloud.discovery.enabled=false
spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration,\
  org.springframework.boot.autoconfigure.security.oauth2.client.servlet.OAuth2ClientAutoConfiguration,\
  org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration
